export {
  useCanvasSizesStore,
  selectCanvasWidth,
  selectCanvasHeight,
  useUserMaterialsStore,
  selectUserMaterials,
  selectAddUserMaterial,
  selectSetUserMaterials,
  useAlignActionStore,
  useSlideStore,
  selectSlideIds,
  selectSlides,
  selectCurrentSlideId,
  selectLastUpdatedAt,
  selectHasUnsavedChanges,
  selectCanUndo,
  selectCanRedo,
  selectPastLength,
  selectCurrentPresentationSlideColor,
  selectSetSlideData,
  selectAddPresentationSlide,
  selectRemovePresentationSlide,
  selectAddCanvasElement,
  selectRemoveCanvasElement,
  selectUpdateCanvasElement,
  selectUpdateCurrentPresentationSlideColor,
  selectBringToFrontCanvasElement,
  selectSendToBackCanvasElement,
  selectSetCurrentSlideId,
  selectMarkChangesAsSaved,
  selectRedo,
  selectUndo,
  type AlignAction,
  type SlideInner,
} from './store';
export {
  canvasElementSchema,
  presentationSlideSchema,
  slideDataSchema,
  CanvasElementType,
  type CanvasElement,
  type PresentationSlide,
  type SlideData,
  type GeometricFigure,
} from './schema';
export { useCurrentPresentationSlide, useSelectedTargets } from './hooks';
export { useCanvas } from './useCanvas';
export { PresentationSlideViewer } from './PresentationSlideViewer';
